# Generated by Django 6.0.1 on 2026-03-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('description', models.TextField(max_length=200)),
                ('price', models.DecimalField(decimal_places=100, max_digits=100)),
                ('stock_count', models.IntegerField(max_length=80)),
                ('published_date', models.DateField(max_length=80)),
                ('is_avaible', models.BooleanField(max_length=80)),
            ],
        ),
    ]
